// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // CLI operations (migrate, studio, db seed) want a direct connection, not
    // Neon's pooler — migrations run session-level locks/DDL that a
    // transaction-mode pooler doesn't support reliably. Runtime queries (see
    // lib/prisma.ts) go through DATABASE_URL (pooled) instead; the fallback
    // here means local dev (no pooler distinction) only needs DATABASE_URL set.
    url: process.env["DATABASE_URL_UNPOOLED"] ?? process.env["DATABASE_URL"],
  },
});
